name: Server Deploy

on:
  push:
    branches: [main]
    paths:
      - 'server/**'

jobs:
  server:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      KAKAO_CLIENT_ID: ${{secrets.KAKAO_CLIENT_ID}}
      KAKAO_CLIENT_SECRET: ${{secrets.KAKAO_CLIENT_SECRET}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        working-directory: ./server
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./server
        run: ./gradlew build

      - name: Docker build
        run: |
          docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
          cd server
          docker build -t celebee-server .
          docker tag celebee-server ${{secrets.DOCKER_HUB_USERNAME}}/celebee-server:v4
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/celebee-server:v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Check if container exists
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^celebee-server$'; then
            docker rm -f celebee-server
          fi
        continue-on-error: true

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.EC2_KEY}}
          host: ${{secrets.EC2_HOST}}
          username: ubuntu
          port: ${{secrets.EC2_PORT}}
          script: |
            whoami
            sudo docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
            sudo docker pull ${{secrets.DOCKER_HUB_USERNAME}}/celebee-server:v4
            sudo docker-compose -f ./docker-compose.yml up -d
